apiVersion: v2
name: booking-app
description: A Helm chart for booking app with Nginx, MySQL and Redis
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: 4.11.3
    repository: https://kubernetes.github.io/ingress-nginx
    condition: nginx.enabled
  - name: ingress-nginx
    alias: ingress-nginx-internal
    version: 4.11.3
    repository: https://kubernetes.github.io/ingress-nginx