apiVersion: v1
kind: Secret
metadata:
  name: {{ include "booking-app.fullname" . }}-secret
  labels:
    {{- include "booking-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: booking-app
type: Opaque
data:
  DB_USERNAME: {{ .Values.mysql.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}