apiVersion: v1
kind: Service
metadata:
  name: {{ include "booking-app.fullname" . }}
  labels:
    {{- include "booking-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: booking-app
spec:
  type: {{ .Values.bookingPlatform.service.type }}
  ports:
    - port: {{ .Values.bookingPlatform.service.port }}
      targetPort: {{ .Values.bookingPlatform.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "booking-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: booking-app