{{- if .Values.internalIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "booking-app.fullname" . }}-internal
  labels:
    {{- include "booking-app.labels" . | nindent 4 }}
  {{- with .Values.internalIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.internalIngress.className }}
  {{- if .Values.internalIngress.tls }}
  tls:
    {{- range .Values.internalIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.internalIngress.hosts }}
    {{- range .Values.internalIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "booking-app.fullname" $ }}
                port:
                  number: {{ $.Values.bookingPlatform.service.port }}
          {{- end }}
    {{- end }}
    {{- else }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "booking-app.fullname" . }}
                port:
                  number: {{ .Values.bookingPlatform.service.port }}
    {{- end }}
{{- end }}