{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "booking-app.mysql.fullname" . }}-init
  labels:
    {{- include "booking-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
data:
  init.sql: {{ .Files.Get "files/init.sql" | quote }}
  init-data.sql: {{ .Files.Get "files/init-data.sql" | quote }}
{{- end }}