apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kafka-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-streams-system.labels" . | fromYaml | toYaml | nindent 4 }}
type: Opaque
data:
  KAFKA_API_KEY: {{ .Values.auth.kafka.apiKey | b64enc | quote }}
  KAFKA_API_SECRET: {{ .Values.auth.kafka.apiSecret | b64enc | quote }}
  SCHEMA_REGISTRY_API_KEY: {{ .Values.auth.schemaRegistry.apiKey | b64enc | quote }}
  SCHEMA_REGISTRY_API_SECRET: {{ .Values.auth.schemaRegistry.apiSecret | b64enc | quote }}