apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "booking-platform.fullname" . }}-config
  labels:
    {{- include "booking-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: booking-platform
data:
  DB_HOST: {{ include "booking-platform.mysql.fullname" . }}
  DB_PORT: "3306"
  REDIS_HOST: {{ include "booking-platform.redis.fullname" . }}
  REDIS_PORT: "6379"