apiVersion: v1
kind: Secret
metadata:
  name: {{ include "booking-platform.fullname" . }}-secret
  labels:
    {{- include "booking-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: booking-platform
type: Opaque
data:
  DB_USERNAME: {{ .Values.mysql.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}