apiVersion: v1
kind: Service
metadata:
  name: {{ include "booking-platform.fullname" . }}
  labels:
    {{- include "booking-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: booking-platform
spec:
  type: {{ .Values.bookingPlatform.service.type }}
  ports:
    - port: {{ .Values.bookingPlatform.service.port }}
      targetPort: {{ .Values.bookingPlatform.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "booking-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: booking-platform